### ISSUE TITLE
Cyclic dependencies 

### ISSUE THREAD

**Issue by barneyhill** [jeffspence/fastDTWF#1]
Great piece of work - very exciting!

Encountered an error due to the setup requiring the library for the VERSION.
```
❯ pip install git+https://github.com/jeffspence/fastDTWF


Collecting git+https://github.com/jeffspence/fastDTWF
  Cloning https://github.com/jeffspence/fastDTWF to /private/var/folders/ks/4xyv63yj03zgqh2vxrfmg6hrb4lqvc/T/pip-req-build-pr8cskkn
  Running command git clone --filter=blob:none --quiet https://github.com/jeffspence/fastDTWF /private/var/folders/ks/4xyv63yj03zgqh2vxrfmg6hrb4lqvc/T/pip-req-build-pr8cskkn
  Resolved https://github.com/jeffspence/fastDTWF to commit cbe4150fa204a73da5cc643a89dd210aa2f57dd7
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ks/4xyv63yj03zgqh2vxrfmg6hrb4lqvc/T/pip-req-build-pr8cskkn/setup.py", line 1, in <module>
          from fastDTWF import VERSION
from fastDTWF import VERSION
import setuptools
        File "/private/var/folders/ks/4xyv63yj03zgqh2vxrfmg6hrb4lqvc/T/pip-req-build-pr8cskkn/fastDTWF/__init__.py", line 1, in <module>
          from fastDTWF.fastDTWF import *
        File "/private/var/folders/ks/4xyv63yj03zgqh2vxrfmg6hrb4lqvc/T/pip-req-build-pr8cskkn/fastDTWF/fastDTWF.py", line 5, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jeffspence** [comment]
Thanks for this!

Should be fixed by https://github.com/jeffspence/fastDTWF/commit/b47dfd816c2913f3320ab20636e936a318aaf227 

Let me know if you run into any other issues!
